// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {logstats} from '../models';

export function AutoDetectToken():Promise<main.UserDTO>;

export function AutoLogin():Promise<main.UserDTO>;

export function Cancel():Promise<void>;

export function ClearLogs():Promise<void>;

export function ClearSession():Promise<void>;

export function ConfigInfo():Promise<main.ConfigInfoDTO>;

export function CountImport(arg1:main.ImportRequest):Promise<main.CountDTO>;

export function DMMessageCount(arg1:string):Promise<number>;

export function DeleteLocalMonitor(arg1:string):Promise<void>;

export function DeleteLog(arg1:string):Promise<void>;

export function DownloadLog(arg1:string):Promise<string>;

export function EnsureIdentity():Promise<main.IdentityDTO>;

export function Enumerate(arg1:main.DeleteRequest):Promise<void>;

export function ExportSearch(arg1:main.LogSearchRequest):Promise<string>;

export function ForgetRemote():Promise<void>;

export function GetPrefs():Promise<main.PrefsDTO>;

export function GetRemote():Promise<main.RemoteDTO>;

export function GetSavedToken():Promise<main.TokenStateDTO>;

export function GuildMessageCount(arg1:string):Promise<number>;

export function HasAutoDetect():Promise<boolean>;

export function ListChannels(arg1:string):Promise<Array<main.ChannelDTO>>;

export function ListGuilds():Promise<Array<main.GuildDTO>>;

export function ListRuns():Promise<Array<logstats.RunStat>>;

export function LoadExport(arg1:string):Promise<main.ExportSummaryDTO>;

export function LocalMonitors():Promise<Array<main.MonitorDTO>>;

export function LogPath():Promise<string>;

export function LogStats():Promise<logstats.Stats>;

export function OpenLogFolder():Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function PickExportFolder():Promise<string>;

export function Preview(arg1:main.DeleteRequest):Promise<number>;

export function PreviewLocalMonitor(arg1:main.MonitorReq):Promise<main.PreviewDTO>;

export function PurgeLogs(arg1:main.LogSearchRequest):Promise<number>;

export function RemoteCancel(arg1:string):Promise<main.JobDTO>;

export function RemoteConnect():Promise<main.ActingAsDTO>;

export function RemoteDeleteMonitor(arg1:string):Promise<void>;

export function RemoteDeleteRun(arg1:string):Promise<void>;

export function RemoteDownloadRun(arg1:string):Promise<string>;

export function RemoteExportJob(arg1:string):Promise<string>;

export function RemoteExportSearch(arg1:main.LogSearchRequest):Promise<string>;

export function RemoteJob(arg1:string):Promise<main.JobDTO>;

export function RemoteJobs():Promise<Array<main.JobDTO>>;

export function RemoteListRuns():Promise<Array<logstats.RunStat>>;

export function RemoteLogStats():Promise<logstats.Stats>;

export function RemoteMonitors():Promise<Array<main.MonitorDTO>>;

export function RemotePairComplete(arg1:string,arg2:string):Promise<main.ActingAsDTO>;

export function RemotePairRequest(arg1:string):Promise<void>;

export function RemotePing():Promise<main.PingDTO>;

export function RemotePreview(arg1:main.RemoteJobRequest):Promise<main.PreviewDTO>;

export function RemotePreviewMonitor(arg1:main.MonitorReq):Promise<main.PreviewDTO>;

export function RemotePurgeLogs(arg1:main.LogSearchRequest):Promise<number>;

export function RemoteRemoveJob(arg1:string):Promise<void>;

export function RemoteRetryJob(arg1:string):Promise<main.JobDTO>;

export function RemoteSearchLogs(arg1:main.LogSearchRequest):Promise<logstats.SearchResult>;

export function RemoteSetMonitor(arg1:main.MonitorReq):Promise<main.MonitorDTO>;

export function RemoteSubmit(arg1:main.RemoteJobRequest):Promise<main.JobDTO>;

export function SampleMessages(arg1:main.DeleteRequest):Promise<Array<main.MessageDTO>>;

export function SearchLogs(arg1:main.LogSearchRequest):Promise<logstats.SearchResult>;

export function SetLocalMonitor(arg1:main.MonitorReq):Promise<main.MonitorDTO>;

export function SetPreScan(arg1:boolean):Promise<void>;

export function SetSkipConfirm(arg1:boolean):Promise<void>;

export function StartDelete(arg1:main.DeleteRequest):Promise<void>;

export function StartImport(arg1:main.ImportRequest):Promise<void>;

export function ValidateToken(arg1:string,arg2:boolean):Promise<main.UserDTO>;
