// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoDetectToken() {
  return window['go']['main']['App']['AutoDetectToken']();
}

export function AutoLogin() {
  return window['go']['main']['App']['AutoLogin']();
}

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ClearSession() {
  return window['go']['main']['App']['ClearSession']();
}

export function ConfigInfo() {
  return window['go']['main']['App']['ConfigInfo']();
}

export function CountImport(arg1) {
  return window['go']['main']['App']['CountImport'](arg1);
}

export function DMMessageCount(arg1) {
  return window['go']['main']['App']['DMMessageCount'](arg1);
}

export function DeleteLocalMonitor(arg1) {
  return window['go']['main']['App']['DeleteLocalMonitor'](arg1);
}

export function DeleteLog(arg1) {
  return window['go']['main']['App']['DeleteLog'](arg1);
}

export function DownloadLog(arg1) {
  return window['go']['main']['App']['DownloadLog'](arg1);
}

export function EnsureIdentity() {
  return window['go']['main']['App']['EnsureIdentity']();
}

export function Enumerate(arg1) {
  return window['go']['main']['App']['Enumerate'](arg1);
}

export function ExportSearch(arg1) {
  return window['go']['main']['App']['ExportSearch'](arg1);
}

export function ForgetRemote() {
  return window['go']['main']['App']['ForgetRemote']();
}

export function GetPrefs() {
  return window['go']['main']['App']['GetPrefs']();
}

export function GetRemote() {
  return window['go']['main']['App']['GetRemote']();
}

export function GetSavedToken() {
  return window['go']['main']['App']['GetSavedToken']();
}

export function GuildMessageCount(arg1) {
  return window['go']['main']['App']['GuildMessageCount'](arg1);
}

export function HasAutoDetect() {
  return window['go']['main']['App']['HasAutoDetect']();
}

export function ListChannels(arg1) {
  return window['go']['main']['App']['ListChannels'](arg1);
}

export function ListGuilds() {
  return window['go']['main']['App']['ListGuilds']();
}

export function ListRuns() {
  return window['go']['main']['App']['ListRuns']();
}

export function LoadExport(arg1) {
  return window['go']['main']['App']['LoadExport'](arg1);
}

export function LocalMonitors() {
  return window['go']['main']['App']['LocalMonitors']();
}

export function LogPath() {
  return window['go']['main']['App']['LogPath']();
}

export function LogStats() {
  return window['go']['main']['App']['LogStats']();
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PickExportFolder() {
  return window['go']['main']['App']['PickExportFolder']();
}

export function Preview(arg1) {
  return window['go']['main']['App']['Preview'](arg1);
}

export function PreviewLocalMonitor(arg1) {
  return window['go']['main']['App']['PreviewLocalMonitor'](arg1);
}

export function PurgeLogs(arg1) {
  return window['go']['main']['App']['PurgeLogs'](arg1);
}

export function RemoteCancel(arg1) {
  return window['go']['main']['App']['RemoteCancel'](arg1);
}

export function RemoteConnect() {
  return window['go']['main']['App']['RemoteConnect']();
}

export function RemoteDeleteMonitor(arg1) {
  return window['go']['main']['App']['RemoteDeleteMonitor'](arg1);
}

export function RemoteDeleteRun(arg1) {
  return window['go']['main']['App']['RemoteDeleteRun'](arg1);
}

export function RemoteDownloadRun(arg1) {
  return window['go']['main']['App']['RemoteDownloadRun'](arg1);
}

export function RemoteExportJob(arg1) {
  return window['go']['main']['App']['RemoteExportJob'](arg1);
}

export function RemoteExportSearch(arg1) {
  return window['go']['main']['App']['RemoteExportSearch'](arg1);
}

export function RemoteJob(arg1) {
  return window['go']['main']['App']['RemoteJob'](arg1);
}

export function RemoteJobs() {
  return window['go']['main']['App']['RemoteJobs']();
}

export function RemoteListRuns() {
  return window['go']['main']['App']['RemoteListRuns']();
}

export function RemoteLogStats() {
  return window['go']['main']['App']['RemoteLogStats']();
}

export function RemoteMonitors() {
  return window['go']['main']['App']['RemoteMonitors']();
}

export function RemotePairComplete(arg1, arg2) {
  return window['go']['main']['App']['RemotePairComplete'](arg1, arg2);
}

export function RemotePairRequest(arg1) {
  return window['go']['main']['App']['RemotePairRequest'](arg1);
}

export function RemotePing() {
  return window['go']['main']['App']['RemotePing']();
}

export function RemotePreview(arg1) {
  return window['go']['main']['App']['RemotePreview'](arg1);
}

export function RemotePreviewMonitor(arg1) {
  return window['go']['main']['App']['RemotePreviewMonitor'](arg1);
}

export function RemotePurgeLogs(arg1) {
  return window['go']['main']['App']['RemotePurgeLogs'](arg1);
}

export function RemoteRemoveJob(arg1) {
  return window['go']['main']['App']['RemoteRemoveJob'](arg1);
}

export function RemoteRetryJob(arg1) {
  return window['go']['main']['App']['RemoteRetryJob'](arg1);
}

export function RemoteSearchLogs(arg1) {
  return window['go']['main']['App']['RemoteSearchLogs'](arg1);
}

export function RemoteSetMonitor(arg1) {
  return window['go']['main']['App']['RemoteSetMonitor'](arg1);
}

export function RemoteSubmit(arg1) {
  return window['go']['main']['App']['RemoteSubmit'](arg1);
}

export function SampleMessages(arg1) {
  return window['go']['main']['App']['SampleMessages'](arg1);
}

export function SearchLogs(arg1) {
  return window['go']['main']['App']['SearchLogs'](arg1);
}

export function SetLocalMonitor(arg1) {
  return window['go']['main']['App']['SetLocalMonitor'](arg1);
}

export function SetPreScan(arg1) {
  return window['go']['main']['App']['SetPreScan'](arg1);
}

export function SetSkipConfirm(arg1) {
  return window['go']['main']['App']['SetSkipConfirm'](arg1);
}

export function StartDelete(arg1) {
  return window['go']['main']['App']['StartDelete'](arg1);
}

export function StartImport(arg1) {
  return window['go']['main']['App']['StartImport'](arg1);
}

export function ValidateToken(arg1, arg2) {
  return window['go']['main']['App']['ValidateToken'](arg1, arg2);
}
